### ISSUE TITLE
Question about adding font!

### ISSUE THREAD

**Issue by lucykim0921** [v1ckych3n/binding#1]
Is there a reason why you're adding both of these codes for importing fonts?:

@import url('https://fonts.googleapis.com/css2?family=Archivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap');

@font-face {
     font-family: Argaka;
     src: url(fonts/ArgakaFashionRegular-K75Bo.ttf);
 }

From what I know, importing just the first part would still work but I wanted to ask what the second part does!

**Comment by v1ckych3n** [comment]
@lucykim0921 

The code
```css
import url('https://fonts.googleapis.com/css2?family=Archivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap');
``` 
is from Google Fonts and their collection for the typeface Archivo. Whereas @fontface 
```css
@font-face {
font-family: Argaka;
src: url(fonts/ArgakaFashionRegular-K75Bo.ttf);
}
``` 
is from a local font file from my computer for the typeface Argaka. I added them in because the font will be there if someone else opens the link from their end. In addition, these fonts will not be a part of my final CSS and website because they were part of the "style in-code" we did earlier for direction-1, direction-2, and direction-3. I am currently styling everything through the common.css file.

**Comment by v1ckych3n** [comment]
@lucykim0921 

The code
```css
import url('https://fonts.googleapis.com/css2?family=Archivo:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&display=swap');
``` 
is from Google Fonts and their collection for the typeface Archivo. Whereas @fontface 
```css
@font-face {
font-family: Argaka;
src: url(fonts/ArgakaFashionRegular-K75Bo.ttf);
}
``` 
is from a local font file from my computer for the typeface Argaka. I added them in because the font will be there if someone else opens the link from their end. In addition, these fonts will not be a part of my final CSS and website because they were part of the "style in-code" we did earlier for direction-1, direction-2, and direction-3. I am currently styling everything through the common.css file.
